DROP TABLE guestbook;

CREATE TABLE guestbook (
	num			NUMBER			CONSTRAINT GUESTBOOK_NUM_PK PRIMARY KEY,
	author		VARCHAR2(50)	CONSTRAINT GUESTBOOK_AUTHOR_NN NOT NULL,
	content		VARCHAR2(1000)	,
	password	VARCHAR2(50)	CONSTRAINT GUESTBOOK_PASSWORD_NN NOT NULL,
	indate		DATE			DEFAULT SYSDATE
);

DROP SEQUENCE guestbook_seq;

CREATE SEQUENCE guestbook_seq;
